name: UltraRepair
version: ${project.version}
main: dev.demeng.ultrarepair.UltraRepair
api-version: 1.13
depend: [Vault]
author: Demeng
description: An advanced item repair/fix plugin featuring cooldowns, costs, bypass permissions, sounds, and more.
website: http://demeng.dev/

commands:
  ultrarepair:
  repair:
    aliases: [fix, repair-hand, fix-hand]
  repairall:
    aliases: [fixall, repair-all, fix-all]