# Config Version
# Do not change this value unless you know what you are doing.
config-version: 2

# Allow players to bypass the Costs
allowBypassCost: true
# Allow players to bypass the Cooldowns
allowBypassCooldown: true
# Enable/Disable the cost system
withCosts: true
# Enable/Disable the cooldown system
withCooldowns: true

# for the heal command
heal:
  # enable/disable the heal command.
  enabled: true

  # Cooldown added for a player after healing, in seconds.
  cooldown: 300

  # The sound played when a heal is completed.
  sound:
    self: "BLOCK_ANVIL_USE"
    other: "BLOCK_ANVIL_USE"

  # Default cost for healing a player.
  default-cost: 10.00
  # multiplier for the cost of healing, based on the amount healed.
  multiplier: 0.00
  # Allow the discount system to be used for healing.
  allowDiscount: true
  # Can Heal be used on other players?
  allow-other: true

# for the feed command
feed:
  # enable/disable the feed command.
  enabled: true

  # Cooldown added for a player after healing, in seconds.
  cooldown: 300

  # The sound played when a feed is completed.
  sound:
    self: "BLOCK_ANVIL_USE"
    other: "BLOCK_ANVIL_USE"

  # Default cost for healing a player.
  default-cost: 10.00
  # multiplier for the cost of healing, based on the amount healed.
  multiplier: 0.00
  # Allow the discount system to be used for healing.
  allowDiscount: true
  # Allow automatic feeding when a player is hungry.
  auto-feed: true
  # Can feed be used on other players?
  allow-other: true

# for the repair command
repair:
  # enable/disable the repair command.
  enabled: true

  # The cooldown added for a player after repairing an item, in seconds.
  # Note that cooldowns do NOT persist across server restarts
  cooldown:
    # The cooldown for hand repairs.
    hand: 10
    # The cooldown for inventory repairs.
    all: 20

  # The sound played when a repair is completed.
  sound:
    hand: "BLOCK_ANVIL_USE"
    all: "BLOCK_ANVIL_USE"

  # The default, base cost for repairing an item.
  # Note that costs are IGNORED if you do not have Vault and an economy plugin installed.
  default-cost: 10.00

  # The additional cost multiplier for repairing an item, based on its durability.
  # The durability GAINED in a repair will be multiplied by this and ADDED to the base cost.
  # Example: If repairing 5 durability, and multiplier is 2, $10 will be ADDED to the base cost.
  multiplier: 0.00
  # Allow the discount system to be used for healing.
  allowDiscount: true

  # Items that are exceptions to the default cost. See below for examples.
  cost-exceptions:
    # The Material name of the item. And optional custom name.
    DIAMOND_SWORD:
      cost: 50.0
      custom-name: "Legendary Sword"
    IRON_PICKAXE:
      cost: 30.0

# for the nightvision command
nv:
  # enable/disable the nightvision command.
  enabled: true

  # Cooldown added for a player after using nightvision, in seconds.
  # Default: 43.200 (12 hours)
  cooldown: 43200

  # Duration of the nightvision effect, in seconds.
  # Default: 14.400 (4 hours)
  duration: 14400

  # The sound played for the nightvision command
  sound:
    enable: "BLOCK_ANVIL_USE"
    disable: "BLOCK_ANVIL_USE"
    expired: "BLOCK_ANVIL_USE"

  # Default cost for nightvision.
  default-cost: 10.00
  # multiplier for the cost of nightvision, based on the duration.
  multiplier: 0.00

# for the godmode command
god:
  # enable/disable the godmode command.
  enabled: true

  # Cooldown added for a player after using godmode, in seconds.
  # Recommended: 14400 (2 hours)
  cooldown: 0

  # Duration of the godmode, in seconds.
  # Recommended: 1800 (30 mins)
  duration: -1

  # The sound played for the nightvision command
  sound:
    enable: "BLOCK_ANVIL_USE"
    disable: "BLOCK_ANVIL_USE"
    expired: "BLOCK_ANVIL_USE"

  # Default cost for nightvision.
  default-cost: 10.00

  # Fill health when put in god mode?
  # default: false
  heal-on-godmode: false

  # Fill hunger when put in god mode?
  # default: false
  feed-on-godmode: false

# for the admin command
admin:
  # enable/disable the admin command.
  enabled: true

  # name of the track to use for the ranks. DEPENDS ON THE TRACKS CONFIGURATION AND LUCKPERMS
  # Default: "ranks"
  track-name: "ranks"

  # Automatically kick a player if they are banned
  auto-kick: true

  # Can the admin commands be enabled/disabled?
  always-on: false

  # Commands which can always be run by players with the required permission.
  always-on-commands:
    - "on"
    - "off"
    - "status"
    - "help"
    - "reload"
    - "stop"
    - "restart"

  # From what permission level certain admin commands can be run.
  # Only "admin" and "helper" are supported. Accessible under the "customtools.admin" and "customtools.helper" permission.
  commands:
    helper:
      - "kick"
      - "mute"
      - "unmute"
      - "ban"
      - "unban"
      - "eco"
      - "world"
      - "perf"
      - "status"
      - "specs"
      - "reload"
      - "stop"
      - "help"
      - "world"
    admin:
      - "on"
      - "off"
      - "rank"

  # The sound played for the nightvision command
  sound:
    enable: "BLOCK_ANVIL_USE"
    disable: "BLOCK_ANVIL_USE"

ec:
  # enable/disable the ec (Enderchest) command.
  enabled: true

  # Cooldown added for a player after using ec, in seconds.
  # Default: -1 (Always)
  cooldown: 0

  # Allow players to open other players' Enderchest (if they have permission).
  allow-other: true

  # Default cost for ec command
  default-cost: 0

  # Allow the discount system to be used for ec command.
  allowDiscount: true

  # The multiplier based on the player level for the cost of ec command.
  multiplier: 0.00

  # Cost Exceptions for specific Players
  cost-exceptions:
    # Name of the player
    # The cost to open their ec
    - _Notch: 10.00

  # The sound played for the ec command
  sound:
    self: "BLOCK_ANVIL_USE"
    other: "BLOCK_ANVIL_USE"

blockportals:
  # enable/disable the blockportals functionality.
  enabled: true

  # players with creative gamemode can bypass this
  allow-bypass: true
  always-allow-creative: true

  # specifies which destinations (other worlds) are allowed in the specified world
  # put a list of world names here, or leave empty to allow all worlds
  worlds:
    world: ["world_the_end"]
    world_nether: ["world"]
    world_the_end: []

  # uses value as default if a world is not specified
  deny-as-default: true

whitelist:
  # enable/disable the whitelist command.
  enabled: true
  # enable/disable the whitelist of the server.
  enabled-whitelist: false
  # allows modifying the whitelist command
  allow-modify: true
  # use the pre-login event to check if a player is whitelisted
  # if false, the default login event will be used instead
  use-preloginEvent: true
  # duration of for being white-listed. -1 for permanent
  default-duration: -1
  # case parsing mode
  # "ignore" - ignore case
  # "lower" - convert to lower case
  # "upper" - convert to upper case
  case-mode: "ignore"

  not_whitelisted:
    - "&cYou're not whitelisted on this server!"
    - "&cPlease contact an admin to be whitelisted!"
    - "&9Visit the discord server for more info!"

  sound:
    add: "BLOCK_ANVIL_USE"
    remove: "BLOCK_ANVIL_USE"
    on: "BLOCK_ANVIL_USE"
    off: "BLOCK_ANVIL_USE"

  # save the whitelist to a file
  whitelisted: []
