name: CustomTools
version: 1.0.0
main: dev.julizey.customtools.CustomTools
api-version: 1.21
softdepend: [Vault]
author: Julizey
description: A plugin for useful commands such as repair, heal, feed, nightvisio, and godmode for players.

commands:
  repair:
    usage: /repair
    description: repairs an item in your hand
  heal:
    usage: /heal
    description: heals you to full health
  feed:
    usage: /feed
    description: fills your hunger bar to full
  god:
    usage: /god
    description: gives you god mode (for a short time)
  nv:
    usage: /nv
    description: gives you night vision for a short time
  ec:
    usage: /ec
    description: opens the enderchest
  admin:
    usage: /admin <subcommand>
    description: useful commands for admins
  blockportals:
    usage: /blockportals <subcommand>
    description: blocks portals from being used by players
  whitelist:
    usage: /whitelist <subcommand>
    description: manages the whitelist of the server

permissions:
  customtools.*:
    description: Gives access to all Inferno commands
    default: op
    children:
      customtools.reload: true
      customtools.repair: true
      customtools.heal: true
      customtools.feed: true
      customtools.god: true
      customtools.nv: true
  customtools.reload:
    description: Allows you to reload the configs of the plugin
    default: op
  customtools.admin:
    description: Allows to use admin commands
    default: op
  customtools.helper:
    description: Allows to use helper commands
    default: op

  customtools.repair:
    description: Repairs items in your hand or inventory
    default: true
    children:
      customtools.repair.use: true
      customtools.repair.all: true
  customtools.repair.use:
    description: repair items in your hand
    default: true
  customtools.repair.all:
    description: Repairs all items in your inventory
    default: true

  customtools.heal:
    description: Heals you to full health
    default: true
    children:
      customtools.heal.use: true
      customtools.heal.other: false
  customtools.heal.use:
    description: Heals yourself to full health
    default: true
  customtools.heal.other:
    description: Heals another player to full health
    default: op

  customtools.feed:
    description: Feeds you to full hunger
    default: true
    children:
      customtools.feed.other: false
      customtools.feed.use: true
  customtools.feed.use:
    default: true
    description: Feeds yourself to full hunger
  customtools.feed.other:
    description: Feeds another player to full hunger
    default: op

  customtools.nv:
    description: Allows to enable/disable night vision for yourself
    default: true
    children:
      customtools.nv.other: false
      customtools.nv.use: true
  customtools.nv.use:
    description: enable/disable night vision for yourself
    default: true
  customtools.nv.other:
    description: enable/disable night vision for another player
    default: op

  customtools.god:
    description: Allows to enable/disable invincibility for yourself
    default: true
    children:
      customtools.god.other: false
      customtools.god.use: true
  customtools.god.use:
    description: enable/disable invincibility for yourself
    default: true
  customtools.god.other:
    description: enable/disable invincibility for another player
    default: op

  customtools.ec:
    description: Opens the Ender Chest
    default: true
    children:
      customtools.ec.other: false
      customtools.ec.use: true
  customtools.ec.use:
    description: opens the Ender Chest for yourself
    default: true
  customtools.ec.other:
    description: opens the Ender Chest for another player
    default: op

  customtools.blockportals.bypass:
    description: Allows to bypass the restrictions
  customtools.blockportals.worlds.<world>.*:
    description: Allows to use all portals in the world
  customtools.blockportals.worlds.<world>.<dest>:
    description: Allows to use portals of the type in the world

  customtools.whitelist.view:
    description: Allows to view the whitelist
    default: op
  customtools.whitelist.modify:
    description: Allows to view the whitelist
    default: op
